### ISSUE TITLE
rlx | Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by pfrancois** [tmpfs/rlx#10]
i have just instal rlx and the only thing i can do is rlx --help and rlx --version (version 0.3.2).
and what ever i type;, the erroe is "rlx | Cannot read property 'match' of undefined".

**Comment by tmpfs** [comment]
Working fine for me.

Can you please do this:

1. Start couchdb locally
2. Run `NODE_ENV=devel rlx info -s :lh`

And post the resulting output here, it should include the stack trace for the error.

Thanks.

**Comment by tmpfs** [comment]
I am guessing after a quick search the the `rc` logic has gone awry:

https://github.com/tmpfs/rlx/blob/master/lib/rlx.js#L153-L164

**Comment by pfrancois** [comment]
when i run your statement: i have this .

rlx | Cannot read property 'match' of undefined
rlx |   conf.rc.onload (C:\Users\francois\AppData\Roaming\npm\node_modules\rlx\lib\rlx.js:154:27)
rlx |   C:\Users\francois\AppData\Roaming\npm\node_modules\rlx\node_modules\cli-mid-rc\index.js:62:23
rlx |   C:\Users\francois\AppData\Roaming\npm\node_modules\rlx\node_modules\cli-rc\index.js:142:5
rlx |   C:\Users\francois\AppData\Roaming\npm\node_modules\rlx\node_modules\cli-rc\node_modules\async\lib\async.js:52:16
rlx |   C:\Users\francois\AppData\Roaming\npm\node_modules\rlx\node_modules\cli-rc\node_modules\async\lib\async.js:363:13
rlx |   C:\Users\francois\AppData\Roaming\npm\node_modules\rlx\node_modules\cli-rc\node_modules\async\lib\async.js:52:16
rlx |   C:\Users\francois\AppData\Roaming\npm\node_modules\rlx\node_modules\cli-rc\node_modules\async\lib\async.js:272:32
rlx |   C:\Users\francois\AppData\Roaming\npm\node_modules\rlx\node_modules\cli-rc\node_modules\async\lib\async.js:44:16
rlx |   C:\Users\francois\AppData\Roaming\npm\node_modules\rlx\node_modules\cli-rc\node_modules\async\lib\async.js:360:17
rlx |   C:\Users\francois\AppData\Roaming\npm\node_modules\rlx\node_modules\cli-rc\index.js:121:26

**Comment by tmpfs** [comment]
Ah, I think I see the issue, it appears you are using Windows. From the readme:

> Command line interface for couchdb designed for POSIX systems.

I don't have access to a Windows machine and there are currently no plans to support Windows. You may install Cygwin of another of the *NIX emulators for Windows and it *should* work (if you try let me know how it goes).

Alternatively, if you really want to use this tool on Windows please raise a separate issue *Windows support*, but if you do, I would need *a lot* of help stepping through the issues/bugs.

Closing this as not an issue.
