### ISSUE TITLE
Creating multiple docs and how to attach a JSON file?

### ISSUE THREAD

**Issue by LarsVoith** [tmpfs/rlx#13]
Is it possible to create multiple docs with a JSON file using "db bulk"?
If so could you provide an example of the syntax?

Example:
POST /source/_bulk_docs HTTP/1.1
Accept: application/json
Content-Length: 323
Content-Type: application/json
Host: localhost:5984
{
    "docs": [
        {
            "_id": "FishStew",
            "servings": 4,
            "subtitle": "Delicious with freshly baked bread",
            "title": "FishStew"
        },
        {
            "_id": "LambStew",
            "servings": 6,
            "subtitle": "Serve with a whole meal scone topping",
            "title": "LambStew"
        },
        {
            "servings": 8,
            "subtitle": "Hand-made dumplings make a great accompaniment",
            "title": "BeefStew"
        }
    ]
}

**Comment by tmpfs** [comment]
Hey - you should be able to use the `bulk push` command and pass a directory containing documents.

The test spec:

https://github.com/tmpfs/rlx/blob/master/test/spec/bulk/lifecycle.js#L42-L52

Which runs with these arguments:

https://github.com/tmpfs/rlx/blob/master/test/fixtures/bulk.js#L30-L43

Which just points to this directory (as the last argument):

https://github.com/tmpfs/rlx/tree/master/test/fixtures/app/docs 

So it should be:

```
rlx bulk push -s http://localhost:5984 -d mydb /path/to/files
```

You may also want to check out the `app` command that also allows adding design documents, rewrites etc.

The full directory structure for an `app` is here:

https://github.com/tmpfs/rlx/tree/master/test/fixtures/app

If you also want to create attachments, create a folder with an `index.json` file and other files will be considered attachments.

I know the documentation needs some more work, but I hope that helps.
